name: movementforfertility
favicon: null
layout_spectrum: 0.21240464807488024
typography_spectrum: 0.7872311971150339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6ccf9'
    - '#542a4f'
    - '#3c0c3f'
    - '#7d587f'
    - '#ad8db7'
  brandStrength: 1
  lightness: 0.04522387753240764
  saturation: 0.32440606434829533
  rhythmicContrast: 0.9779010280035436
purpose: []
